spring:
  application:
    name: authbasics
  datasource:
    url: jdbc:h2:mem:mydb
    driver-class-name: org.h2.Driver
    username: sa
    password: 12345
  sql:
    init:
      schema: classpath:schema.sql
      data: classpath:data.sql
      mode: always
